parameters:
    phobetor_rabbitmq_supervisor.rabbitmq_supervisor_service.class: Phobetor\RabbitMqSupervisorBundle\Services\RabbitMqSupervisor
    phobetor_rabbitmq_supervisor.supervisor_service.class: Phobetor\RabbitMqSupervisorBundle\Services\Supervisor

services:
    phobetor_rabbitmq_supervisor:
        class: "%phobetor_rabbitmq_supervisor.rabbitmq_supervisor_service.class%"
        arguments:
            - "@phobetor_rabbitmq_supervisor.supervisor_service"
            - "@templating"
            - "%phobetor_rabbitmq_supervisor.paths%"
            - "%phobetor_rabbitmq_supervisor.commands%"
            - "%phobetor_rabbitmq_supervisor.consumers%"
            - "%phobetor_rabbitmq_supervisor.multiple_consumers%"
            - "%phobetor_rabbitmq_supervisor.worker_count%"
            - "%phobetor_rabbitmq_supervisor.worker_options%"

    phobetor_rabbitmq_supervisor.supervisor_service:
        class: "%phobetor_rabbitmq_supervisor.supervisor_service.class%"
        arguments:
            - "%phobetor_rabbitmq_supervisor.workspace%"
            - "%phobetor_rabbitmq_supervisor.configuration_file%"
            - "%phobetor_rabbitmq_supervisor.supervisor_instance_identifier%"
